# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Woochal"
description: > # this means to ignore newlines until "email:"
   Welcome to W.C Universe - 2nd Colony

email: Woochal@gmail.com
#blog logo
logo: "/assets/images/wc_logo.jpeg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/astronaut-wallpaper.jpg"

name: 'Woochal Park'
author: 'Woochal Park'
author_image: "/assets/images/smile.jpeg"

paginate:	5

url: "https://chat.openai.com/" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@Woochal'

#fill in disqus shortname to use disqus
#disqus: Woochal

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://www.youtube.com/watch?v=VdeK_VsG9U0&ab_channel=AOMGOFFICIAL
    desc: He He
    share_url: https://www.youtube.com/watch?v=VdeK_VsG9U0&ab_channel=AOMGOFFICIAL
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/Woochal
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
